heat_template_version: 2013-05-23
description: >
  A simple Heat template to deploy CoreOS into magnum.
parameters:
  network_id:
    type: string
    label: Network ID
    description: ID of existing Neutron network to use
    default: 067a3a85-dd89-46b2-83d2-9fb7cabd5efd
  image_id:
    type: string
    label: CoreOS
    description: ID of existing Glance image to use
    default: 97b472cc-29bb-4f21-8e78-d18f7646d29c
resources:
  instance0_port0:
    type: OS::Neutron::Port
    properties:
      admin_state_up: true
      network_id: { get_param: network_id }
      security_groups:
        - 14672616-8533-48dd-af17-ae56bb5f1971
  instance0:
    type: OS::Nova::Server
    properties:
      name: coreos-04
      image: { get_param: image_id }
      flavor: m1.small
      networks:
        - port: { get_resource: instance0_port0 }
      key_name: testkey
      user_data_format: RAW
      user_data: |
        #cloud-config
        coreos:
          etcd:
            discovery: https://discovery.etcd.io/846790c399f72327af95d2d85c8a3efe
            addr: $private_ipv4:4001
            peer-addr: $private_ipv4:7001
          units:
            - name: etcd.service
              command: start
            - name: fleet.service
              command: start
          ssh_authorized_keys:
            - testkey
          hostname: coreos-04
